### ISSUE TITLE
Sass compile error

### ISSUE THREAD

**Issue by FLasH3r** [perichus/wire.css#4]
I'm getting sass compile error:

error vendor/wirecss/wire.scss (Line 392 of vendor/wirecss/components/_grid.scss: Mixins may not be defined within control directives or
 other mixins.)

Am I missing something ? I'm using compass watch to compile changes, but I'm guessing I have a wrong version or something like that...

Appreciate the help or point in the right direction :)

**Comment by FLasH3r** [comment]
never mind, `gem update` fixed the issue :)

**Comment by FLasH3r** [comment]
after `gem update` still the same

**Comment by perichus** [comment]
@FLasH3r Sass & Compass version?

**Comment by FLasH3r** [comment]
Compass 1.0.3 (Polaris)
Sass 3.4.22 (Selective Steve)

**Comment by perichus** [comment]
Are you using an older Wire.css version? I fix that error in 1.2.4 release.

I can reproduce that error using 1.2.3 version.

What Wire.css version are you using?

**Comment by FLasH3r** [comment]
I clicked the download link from the site which points to http://wirecss.com/zips/wire-latest.source.zip

In this page: https://wirecss.com/docs/getting-started/installation

**Comment by perichus** [comment]
Download it again and check, I just update the zip (wrong version zipped).

Sorry for the inconvenience.

**Comment by FLasH3r** [comment]
Works great! 
Looks very promising 👍
